##3:

#line 53 "spider.web"

BEGIN{
##9:

#line 181 "spider.web"

#line 182 "spider.web"
logfile="spider.slog"

##:9
##10:

#line 185 "spider.web"

#line 186 "spider.web"
translationfile="trans_keys.unsorted"

##:10
##11:

#line 190 "spider.web"

#line 191 "spider.web"
scrapfile="scraps.web"
print"@*Scrap code generated by {\\tt SPIDER}.">scrapfile
ttokfile="outtoks.web"
print"@*Token code generated by {\\tt SPIDER}.">ttokfile
##:11
##12:

#line 197 "spider.web"

#line 198 "spider.web"
reserved="scraps.web"

##:12
##13:

#line 202 "spider.web"

#line 203 "spider.web"
tokennamefile="names.unsorted"
##:13
##14:

#line 206 "spider.web"

#line 207 "spider.web"
ilkfile="names.unsorted"
##:14
##15:

#line 210 "spider.web"

#line 211 "spider.web"
categoryfile="names.unsorted"
##:15
##16:

#line 213 "spider.web"

#line 214 "spider.web"
grammarfile="grammar.web"
print"@*Grammar code generated by {\\tt SPIDER}.">grammarfile
##:16
##17:

#line 219 "spider.web"

#line 220 "spider.web"
tlang="outtoks.web"
wlang="scraps.web"

##:17
##18:

#line 225 "spider.web"

#line 226 "spider.web"
productions="productions.list"

##:18
##19:

#line 229 "spider.web"

#line 230 "spider.web"
cycles="cycle.test"



##:19
##37:

#line 525 "spider.web"

#line 526 "spider.web"
default_translation="<*>"
default_mathness="maybe"


##:37
##46:

#line 727 "spider.web"

#line 728 "spider.web"
highesttoken=200
tokennumber=highesttoken

##:46
##61:

#line 943 "spider.web"

#line 944 "spider.web"
tokennumbers["identifier"]=tokennumber;tokennumber--
tokenname["identifier"]="identifier"

##:61
##63:

#line 969 "spider.web"

#line 970 "spider.web"
tokennumbers["constant"]=tokennumber;tokennumber--
tokenname["constant"]="constant"
tokennumbers["string"]=tokennumber;tokennumber--
tokenname["string"]="string"


##:63
##138:

#line 2246 "spider.web"

#line 2247 "spider.web"
at_sign="@@"


##:138
##146:

#line 2397 "spider.web"

#line 2398 "spider.web"
texof["\\"]="\\BS"
texof["{"]="\\{"
texof["}"]="\\{"
texof["$"]="\\$"
texof["&"]="\\amp"
texof["#"]="\\#"
texof["^"]="\\H"
texof["_"]="\\_"
texof["~"]="\\TI"
texof["%"]="\\%"

##:146
##150:

#line 2475 "spider.web"

#line 2476 "spider.web"
sharp_line_open="\"#line\""
sharp_line_close="\"\""

##:150
##152:

#line 2495 "spider.web"

#line 2496 "spider.web"
month["Jan"]="January"
month["Feb"]="February"
month["Mar"]="March"
month["Apr"]="April"
month["May"]="May"
month["Jun"]="June"
month["Jul"]="July"
month["Aug"]="August"
month["Sep"]="September"
month["Oct"]="October"
month["Nov"]="November"
month["Dec"]="December"

##:152

#line 55 "spider.web"

exitcode=0
}

##6:

#line 100 "spider.web"

#line 101 "spider.web"
/^#|^ *$/{

print $0>logfile
next
}

##:6

#line 59 "spider.web"

##35:

#line 498 "spider.web"

#line 499 "spider.web"
/^default /{
print"Setting defaults...">logfile
start_place=2
##36:

#line 518 "spider.web"

#line 519 "spider.web"
this_translation=default_translation
this_mathness=default_mathness
this_name=""
this_category=""
this_tangleto=""
##:36

#line 503 "spider.web"

##29:

#line 434 "spider.web"

#line 435 "spider.web"
for(i=start_place;i<NF;){
if($i=="tangleto"){
i++
this_tangleto=$i
i++
}else if($i=="translation"){
i++
this_translation=$i
i++
}else if($i=="mathness"){
i++
this_mathness=$i
i++
}else if($i=="category"){
i++
this_category=$i
categories[$i]=1
i++
}else if($i=="name"){
i++
this_name="SP_"$i
i++
}else{
print"Error: unrecognized token description",$i,"on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 459 "spider.web"

}
}
##5:

#line 91 "spider.web"

#line 92 "spider.web"
if(i<=NF){
print"Error: leftover fields",$i,"... on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 94 "spider.web"

}


##:5

#line 462 "spider.web"


##:29

#line 506 "spider.web"

##30:

#line 466 "spider.web"

#line 467 "spider.web"
if(this_name!=""){
print"Error: name doesn't apply on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 469 "spider.web"

}
##:30

#line 507 "spider.web"

##32:

#line 476 "spider.web"

#line 477 "spider.web"
if(this_category!=""){
print"Error: category doesn't apply on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 479 "spider.web"

}
##:32

#line 508 "spider.web"

default_translation=this_translation
default_mathness=this_mathness
print"\tdefault translation is",default_translation>logfile
print"\tdefault mathness is",default_mathness>logfile
next
}

##:35
##39:

#line 570 "spider.web"

#line 571 "spider.web"
/^token /{
print"Token",$2>logfile
if($2=="identifier"){
##40:

#line 595 "spider.web"

#line 596 "spider.web"
##36:

#line 518 "spider.web"

#line 519 "spider.web"
this_translation=default_translation
this_mathness=default_mathness
this_name=""
this_category=""
this_tangleto=""
##:36

#line 597 "spider.web"

this_translation=""
start_place=3
##29:

#line 434 "spider.web"

#line 435 "spider.web"
for(i=start_place;i<NF;){
if($i=="tangleto"){
i++
this_tangleto=$i
i++
}else if($i=="translation"){
i++
this_translation=$i
i++
}else if($i=="mathness"){
i++
this_mathness=$i
i++
}else if($i=="category"){
i++
this_category=$i
categories[$i]=1
i++
}else if($i=="name"){
i++
this_name="SP_"$i
i++
}else{
print"Error: unrecognized token description",$i,"on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 459 "spider.web"

}
}
##5:

#line 91 "spider.web"

#line 92 "spider.web"
if(i<=NF){
print"Error: leftover fields",$i,"... on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 94 "spider.web"

}


##:5

#line 462 "spider.web"


##:29

#line 602 "spider.web"

##30:

#line 466 "spider.web"

#line 467 "spider.web"
if(this_name!=""){
print"Error: name doesn't apply on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 469 "spider.web"

}
##:30

#line 603 "spider.web"

##31:

#line 471 "spider.web"

#line 472 "spider.web"
if(this_tangleto!=""){
print"Error: tangleto doesn't apply on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 474 "spider.web"

}
##:31

#line 604 "spider.web"

##34:

#line 486 "spider.web"

#line 487 "spider.web"
if(this_category==""){
print"Error: you must give a category on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 489 "spider.web"

}

##:34

#line 605 "spider.web"

##33:

#line 481 "spider.web"

#line 482 "spider.web"
if(this_translation!=""){
print"Error: translation doesn't apply on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 484 "spider.web"

}
##:33

#line 606 "spider.web"

id_category=this_category
id_mathness=this_mathness

##:40

#line 574 "spider.web"

}else if($2=="number"){
##41:

#line 611 "spider.web"

#line 612 "spider.web"
print"Warning: numeric constants and strings are",\
"identified in this WEAVE."
print"Warning: numeric constants and strings are",\
"identified in this WEAVE.">logfile
##36:

#line 518 "spider.web"

#line 519 "spider.web"
this_translation=default_translation
this_mathness=default_mathness
this_name=""
this_category=""
this_tangleto=""
##:36

#line 617 "spider.web"

this_translation=""
start_place=3
##29:

#line 434 "spider.web"

#line 435 "spider.web"
for(i=start_place;i<NF;){
if($i=="tangleto"){
i++
this_tangleto=$i
i++
}else if($i=="translation"){
i++
this_translation=$i
i++
}else if($i=="mathness"){
i++
this_mathness=$i
i++
}else if($i=="category"){
i++
this_category=$i
categories[$i]=1
i++
}else if($i=="name"){
i++
this_name="SP_"$i
i++
}else{
print"Error: unrecognized token description",$i,"on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 459 "spider.web"

}
}
##5:

#line 91 "spider.web"

#line 92 "spider.web"
if(i<=NF){
print"Error: leftover fields",$i,"... on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 94 "spider.web"

}


##:5

#line 462 "spider.web"


##:29

#line 622 "spider.web"

##30:

#line 466 "spider.web"

#line 467 "spider.web"
if(this_name!=""){
print"Error: name doesn't apply on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 469 "spider.web"

}
##:30

#line 623 "spider.web"

##31:

#line 471 "spider.web"

#line 472 "spider.web"
if(this_tangleto!=""){
print"Error: tangleto doesn't apply on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 474 "spider.web"

}
##:31

#line 624 "spider.web"

##34:

#line 486 "spider.web"

#line 487 "spider.web"
if(this_category==""){
print"Error: you must give a category on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 489 "spider.web"

}

##:34

#line 625 "spider.web"

##33:

#line 481 "spider.web"

#line 482 "spider.web"
if(this_translation!=""){
print"Error: translation doesn't apply on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 484 "spider.web"

}
##:33

#line 626 "spider.web"

number_category=this_category
number_mathness=this_mathness

##:41

#line 576 "spider.web"

}else if($2=="newline"){
##42:

#line 631 "spider.web"

#line 632 "spider.web"
##36:

#line 518 "spider.web"

#line 519 "spider.web"
this_translation=default_translation
this_mathness=default_mathness
this_name=""
this_category=""
this_tangleto=""
##:36

#line 633 "spider.web"

start_place=3
##29:

#line 434 "spider.web"

#line 435 "spider.web"
for(i=start_place;i<NF;){
if($i=="tangleto"){
i++
this_tangleto=$i
i++
}else if($i=="translation"){
i++
this_translation=$i
i++
}else if($i=="mathness"){
i++
this_mathness=$i
i++
}else if($i=="category"){
i++
this_category=$i
categories[$i]=1
i++
}else if($i=="name"){
i++
this_name="SP_"$i
i++
}else{
print"Error: unrecognized token description",$i,"on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 459 "spider.web"

}
}
##5:

#line 91 "spider.web"

#line 92 "spider.web"
if(i<=NF){
print"Error: leftover fields",$i,"... on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 94 "spider.web"

}


##:5

#line 462 "spider.web"


##:29

#line 637 "spider.web"

##30:

#line 466 "spider.web"

#line 467 "spider.web"
if(this_name!=""){
print"Error: name doesn't apply on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 469 "spider.web"

}
##:30

#line 638 "spider.web"

##31:

#line 471 "spider.web"

#line 472 "spider.web"
if(this_tangleto!=""){
print"Error: tangleto doesn't apply on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 474 "spider.web"

}
##:31

#line 639 "spider.web"

##34:

#line 486 "spider.web"

#line 487 "spider.web"
if(this_category==""){
print"Error: you must give a category on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 489 "spider.web"

}

##:34

#line 640 "spider.web"

newline_category=this_category
newline_mathness=this_mathness
newline_translation=this_translation

##:42

#line 578 "spider.web"

}else if($2=="pseudo_semi"){
##43:

#line 646 "spider.web"

#line 647 "spider.web"
##36:

#line 518 "spider.web"

#line 519 "spider.web"
this_translation=default_translation
this_mathness=default_mathness
this_name=""
this_category=""
this_tangleto=""
##:36

#line 648 "spider.web"

start_place=3
##29:

#line 434 "spider.web"

#line 435 "spider.web"
for(i=start_place;i<NF;){
if($i=="tangleto"){
i++
this_tangleto=$i
i++
}else if($i=="translation"){
i++
this_translation=$i
i++
}else if($i=="mathness"){
i++
this_mathness=$i
i++
}else if($i=="category"){
i++
this_category=$i
categories[$i]=1
i++
}else if($i=="name"){
i++
this_name="SP_"$i
i++
}else{
print"Error: unrecognized token description",$i,"on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 459 "spider.web"

}
}
##5:

#line 91 "spider.web"

#line 92 "spider.web"
if(i<=NF){
print"Error: leftover fields",$i,"... on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 94 "spider.web"

}


##:5

#line 462 "spider.web"


##:29

#line 652 "spider.web"

##30:

#line 466 "spider.web"

#line 467 "spider.web"
if(this_name!=""){
print"Error: name doesn't apply on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 469 "spider.web"

}
##:30

#line 653 "spider.web"

##31:

#line 471 "spider.web"

#line 472 "spider.web"
if(this_tangleto!=""){
print"Error: tangleto doesn't apply on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 474 "spider.web"

}
##:31

#line 654 "spider.web"

##34:

#line 486 "spider.web"

#line 487 "spider.web"
if(this_category==""){
print"Error: you must give a category on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 489 "spider.web"

}

##:34

#line 655 "spider.web"

pseudo_semi_category=this_category
pseudo_semi_mathness=this_mathness
pseudo_semi_translation=this_translation

##:43

#line 580 "spider.web"

}else if($2~/[a-zA-ZA-Z0-9]+/){

print"Error: unknown token species:",$2
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 584 "spider.web"

}else{
##44:

#line 677 "spider.web"

#line 678 "spider.web"
this_string=$2
##45:

#line 700 "spider.web"

#line 701 "spider.web"
old_string=this_string
this_string=""


idx=index(old_string,"{space}")
while(idx!=0){
temp=substr(old_string,1,idx-1)
this_string=this_string temp" "
old_string=substr(old_string,idx+7)
idx=index(old_string,"{space}")
}
this_string=this_string old_string

##:45

#line 679 "spider.web"


$2=this_string

##49:

#line 767 "spider.web"

#line 768 "spider.web"
if($2=="@"){
$2="@@"
tokenname[$2]="'@@'"
tokenlength[$2]=1
}else if($2=="'"||$2=="\\"){
$2="\\"$2
tokenname[$2]="'"$2"'"
tokenlength[$2]=1
}else if(length($2)>1){
##50:

#line 793 "spider.web"

#line 794 "spider.web"
tokenname[$2]="SP_gen_token_"tokennumber
tokennumbers[$2]=tokennumber
tokennumber--

temp=sprintf("strncmp(\"%s\",loc-1,%d)==0",$2,length($2))
tokentest[$2]=temp
tokenlength[$2]=length($2)


##:50

#line 777 "spider.web"

}else{
temp=sprintf("'%s'",$2)
tokenname[$2]=temp
tokenlength[$2]=1
}

##:49

#line 684 "spider.web"

if(tokens[$2]!=""){
print"Warning: token",$2,"defined twice"
}
tokens[$2]=1
##51:

#line 804 "spider.web"

#line 805 "spider.web"
##36:

#line 518 "spider.web"

#line 519 "spider.web"
this_translation=default_translation
this_mathness=default_mathness
this_name=""
this_category=""
this_tangleto=""
##:36

#line 806 "spider.web"

this_name=tokenname[$2]
start_place=3
##29:

#line 434 "spider.web"

#line 435 "spider.web"
for(i=start_place;i<NF;){
if($i=="tangleto"){
i++
this_tangleto=$i
i++
}else if($i=="translation"){
i++
this_translation=$i
i++
}else if($i=="mathness"){
i++
this_mathness=$i
i++
}else if($i=="category"){
i++
this_category=$i
categories[$i]=1
i++
}else if($i=="name"){
i++
this_name="SP_"$i
i++
}else{
print"Error: unrecognized token description",$i,"on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 459 "spider.web"

}
}
##5:

#line 91 "spider.web"

#line 92 "spider.web"
if(i<=NF){
print"Error: leftover fields",$i,"... on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 94 "spider.web"

}


##:5

#line 462 "spider.web"


##:29

#line 811 "spider.web"

##34:

#line 486 "spider.web"

#line 487 "spider.web"
if(this_category==""){
print"Error: you must give a category on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 489 "spider.web"

}

##:34

#line 812 "spider.web"

tokencategory[$2]=this_category
tokenmathness[$2]=this_mathness
tokentranslation[$2]=this_translation
tokenname[$2]=this_name
tokentangleto[$2]=this_tangleto

##:51

#line 689 "spider.web"

##53:

#line 828 "spider.web"

#line 829 "spider.web"
if(tokenlength[$2]>1&&tokennumbers[$2]==""){
print"This can't happen: token",$2,"is long",\
"but has no number"
exitcode=-1
}


##:53

#line 690 "spider.web"

##52:

#line 821 "spider.web"

#line 822 "spider.web"
temp=tokenlength[$2]
if(temp>maxtokenlength){
maxtokenlength=temp
}

##:52

#line 691 "spider.web"



##:44

#line 586 "spider.web"

}
categories[this_category]=1

next
}

##:39
##75:

#line 1183 "spider.web"

#line 1184 "spider.web"
/^ilk /{
print"Ilk",$2>logfile
##36:

#line 518 "spider.web"

#line 519 "spider.web"
this_translation=default_translation
this_mathness=default_mathness
this_name=""
this_category=""
this_tangleto=""
##:36

#line 1187 "spider.web"

##76:

#line 1206 "spider.web"

#line 1207 "spider.web"
if($2~/^[a-zA-Z_]+_like$/&&$0!~/ category /){

this_category=substr($2,1,length($2)-5)
categories[this_category]=1
}

##:76

#line 1188 "spider.web"

this_name=""
start_place=3
##29:

#line 434 "spider.web"

#line 435 "spider.web"
for(i=start_place;i<NF;){
if($i=="tangleto"){
i++
this_tangleto=$i
i++
}else if($i=="translation"){
i++
this_translation=$i
i++
}else if($i=="mathness"){
i++
this_mathness=$i
i++
}else if($i=="category"){
i++
this_category=$i
categories[$i]=1
i++
}else if($i=="name"){
i++
this_name="SP_"$i
i++
}else{
print"Error: unrecognized token description",$i,"on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 459 "spider.web"

}
}
##5:

#line 91 "spider.web"

#line 92 "spider.web"
if(i<=NF){
print"Error: leftover fields",$i,"... on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 94 "spider.web"

}


##:5

#line 462 "spider.web"


##:29

#line 1193 "spider.web"

##34:

#line 486 "spider.web"

#line 487 "spider.web"
if(this_category==""){
print"Error: you must give a category on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 489 "spider.web"

}

##:34

#line 1194 "spider.web"

##30:

#line 466 "spider.web"

#line 467 "spider.web"
if(this_name!=""){
print"Error: name doesn't apply on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 469 "spider.web"

}
##:30

#line 1195 "spider.web"

ilk_category[$2]=this_category
ilk_mathness[$2]=this_mathness
ilk_translation[$2]=this_translation
next
}


##:75
##77:

#line 1220 "spider.web"

#line 1221 "spider.web"
/^reserved /{
print"Reserved word",$2>logfile
if($0!~/ ilk /){
##78:

#line 1246 "spider.web"

#line 1247 "spider.web"
temp=$2"_like"
reservedilk[$2]=temp
if(ilk_translation[temp]==""){
ilk_translation[temp]=default_translation
}
has_reserved[temp]=1
if(ilk_mathness[temp]==""){
ilk_mathness[temp]=default_mathness
}

if(ilk_category[temp]==""){
ilk_category[temp]=$2
categories[$2]=1
}
ilk_is_made_up[temp]=1



##:78

#line 1224 "spider.web"

}
for(i=3;i<=NF;){
if($i=="ilk"){
i++
reservedilk[$2]=$i
has_reserved[$i]=1
i++
}else{
print"Error: bad reserved word attribute:",$i,\
"on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 1235 "spider.web"

}
}
##5:

#line 91 "spider.web"

#line 92 "spider.web"
if(i<=NF){
print"Error: leftover fields",$i,"... on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 94 "spider.web"

}


##:5

#line 1238 "spider.web"

next
}

##:77
##129:

#line 2071 "spider.web"

#line 2072 "spider.web"
/^language /{
language=$2
extension=language
for(i=3;i<NF;){
if($i=="extension"){
i++
extension=$i
i++
}else if($i=="version"){
i++
version=$i
i++
}else{
print"Error: unknown language property",$i,\
"on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 2087 "spider.web"

}
}
##5:

#line 91 "spider.web"

#line 92 "spider.web"
if(i<=NF){
print"Error: leftover fields",$i,"... on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 94 "spider.web"

}


##:5

#line 2090 "spider.web"

##131:

#line 2125 "spider.web"

#line 2126 "spider.web"
macrofile=extension"web.tex"
print"\\input webkernel.tex">macrofile


##:131

#line 2091 "spider.web"

next
}

##:129
##132:

#line 2132 "spider.web"

#line 2133 "spider.web"
/^macros begin$/,/^macros end$/{
if(begunmacs==0){
begunmacs=1
next
}
if($0~/^macros end$/){
begunmacs=0
next
}
if(macrofile==""){
if(complained==0){
print"Error: you must give \"language\"",\
"before \"macros\""
complained=1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 2147 "spider.web"

}
}else{
print $0>macrofile
}
next
}



##:132
##133:

#line 2163 "spider.web"

#line 2164 "spider.web"
/^module /{
for(i=2;i<NF;){
if($i=="definition"){
i++
mod_def_cat=$i
categories[$i]=1
print"Module definition category set to",$i>logfile
i++
}else if($i=="use"){
i++
mod_use_cat=$i
categories[$i]=1
print"Module use category set to",$i>logfile
i++
}else{
print"Error: unknown module property",$i,\
"on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 2181 "spider.web"

}
}
##5:

#line 91 "spider.web"

#line 92 "spider.web"
if(i<=NF){
print"Error: leftover fields",$i,"... on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 94 "spider.web"

}


##:5

#line 2184 "spider.web"

next
}

##:133
##135:

#line 2213 "spider.web"

#line 2214 "spider.web"
/^at_sign /{
if(NF==2&&length($2)==1){
if($2=="@"){
at_sign="@@"
}else{
at_sign=$2
}
}else{
print"Error: I can't understand",$0
print"       Give me an at sign of length 1"
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 2224 "spider.web"

}
next
}

##:135
##139:

#line 2254 "spider.web"

#line 2255 "spider.web"
/^comment /{
print $0>logfile
for(i=2;i<NF;){
if($i=="begin"){
i++
if($i~/^<.*>$/){
transstring=$i
wherestring="in \"comment begin\" on line "NR-1
##27:

#line 389 "spider.web"

#line 390 "spider.web"
temp=substr(transstring,2,length(transstring)-2)
trcnt=split(temp,trtok,"-")
outstring=""
for(tridx=1;tridx<=trcnt;tridx++){
alternate=trtok[tridx]
##25:

#line 366 "spider.web"

#line 367 "spider.web"
if(alternate=="space"){
alternate="\" \""
}else if(alternate=="dash"){
alternate="\"-\""
}


##:25

#line 395 "spider.web"

if(alternate~/^[0-9]$/){
print"Digit not allowed in restricted translation",wherestring
exitcode=-1
}else if(alternate~/^[a-zA-Z_]+$/){
print"Key word not allowed in restricted translation",wherestring
exitcode=-1
}else if(alternate~/^\"([^"]*\\\")*[^"]*\"$/){
temp=substr(alternate,2,length(alternate)-2)
outstring=outstring temp
}else if(alternate~/^\*$/){
print"<*> not allowed in restricted translation",wherestring
exitcode=-1
}else{
print"Bogus restricted translation",wherestring
exitcode=-1
}
}
outstring="\""outstring"\""



##:27

#line 2264 "spider.web"

begin_comment_string=outstring
i++
}else{
print"Error: \"comment begin\" must have a restricted translation"
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 2269 "spider.web"

}
}else if($i=="end"){
i++
if($i=="newline"){
comments_end_with_newline=1
end_comment_string="\"\\n\""
}else if($i~/^<.*>$/){
comments_end_with_newline=0
transstring=$i
wherestring="in \"comment end\" on line "NR-1
##27:

#line 389 "spider.web"

#line 390 "spider.web"
temp=substr(transstring,2,length(transstring)-2)
trcnt=split(temp,trtok,"-")
outstring=""
for(tridx=1;tridx<=trcnt;tridx++){
alternate=trtok[tridx]
##25:

#line 366 "spider.web"

#line 367 "spider.web"
if(alternate=="space"){
alternate="\" \""
}else if(alternate=="dash"){
alternate="\"-\""
}


##:25

#line 395 "spider.web"

if(alternate~/^[0-9]$/){
print"Digit not allowed in restricted translation",wherestring
exitcode=-1
}else if(alternate~/^[a-zA-Z_]+$/){
print"Key word not allowed in restricted translation",wherestring
exitcode=-1
}else if(alternate~/^\"([^"]*\\\")*[^"]*\"$/){
temp=substr(alternate,2,length(alternate)-2)
outstring=outstring temp
}else if(alternate~/^\*$/){
print"<*> not allowed in restricted translation",wherestring
exitcode=-1
}else{
print"Bogus restricted translation",wherestring
exitcode=-1
}
}
outstring="\""outstring"\""



##:27

#line 2282 "spider.web"

end_comment_string=outstring
}else{
print"Error: \"comment end\" must have a restricted translation"
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 2286 "spider.web"

}
i++
}else{
print"Error: bad comment attribute:",$i
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 2291 "spider.web"

}
}
##5:

#line 91 "spider.web"

#line 92 "spider.web"
if(i<=NF){
print"Error: leftover fields",$i,"... on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 94 "spider.web"

}


##:5

#line 2294 "spider.web"

##145:

#line 2376 "spider.web"

#line 2377 "spider.web"
if(macrofile!=""){
this_string=substr(begin_comment_string,2,length(begin_comment_string)-2)
##147:

#line 2410 "spider.web"

#line 2411 "spider.web"
tex_string=""
while(length(this_string)>0){
c=substr(this_string,1,1)
this_string=substr(this_string,2)
cprime=texof[c]
if(cprime==""){
tex_string=tex_string c
}else{
tex_string=tex_string cprime
}
}

##:147

#line 2379 "spider.web"

printf"\\def\\commentbegin{%s}\n",tex_string>macrofile
if(comments_end_with_newline==0){
this_string=substr(end_comment_string,2,length(end_comment_string)-2)
##147:

#line 2410 "spider.web"

#line 2411 "spider.web"
tex_string=""
while(length(this_string)>0){
c=substr(this_string,1,1)
this_string=substr(this_string,2)
cprime=texof[c]
if(cprime==""){
tex_string=tex_string c
}else{
tex_string=tex_string cprime
}
}

##:147

#line 2383 "spider.web"

printf"\\def\\commentend{%s}\n",tex_string>macrofile
}else{
print"\\def\\commentend{\\relax}">macrofile
}
}else{
print"Error: I can't write comment info to the macro file---"
print"       you haven't given me any \"language\" information"
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 2391 "spider.web"

}



##:145

#line 2295 "spider.web"

next
}

##:139
##148:

#line 2428 "spider.web"

#line 2429 "spider.web"
/^line /{
print $0>logfile
for(i=2;i<NF;){
if($i=="begin"){
i++
if($i~/^<.*>$/){
transstring=$i
wherestring="in \"line begin\" on line "NR-1
##27:

#line 389 "spider.web"

#line 390 "spider.web"
temp=substr(transstring,2,length(transstring)-2)
trcnt=split(temp,trtok,"-")
outstring=""
for(tridx=1;tridx<=trcnt;tridx++){
alternate=trtok[tridx]
##25:

#line 366 "spider.web"

#line 367 "spider.web"
if(alternate=="space"){
alternate="\" \""
}else if(alternate=="dash"){
alternate="\"-\""
}


##:25

#line 395 "spider.web"

if(alternate~/^[0-9]$/){
print"Digit not allowed in restricted translation",wherestring
exitcode=-1
}else if(alternate~/^[a-zA-Z_]+$/){
print"Key word not allowed in restricted translation",wherestring
exitcode=-1
}else if(alternate~/^\"([^"]*\\\")*[^"]*\"$/){
temp=substr(alternate,2,length(alternate)-2)
outstring=outstring temp
}else if(alternate~/^\*$/){
print"<*> not allowed in restricted translation",wherestring
exitcode=-1
}else{
print"Bogus restricted translation",wherestring
exitcode=-1
}
}
outstring="\""outstring"\""



##:27

#line 2438 "spider.web"

sharp_line_open=outstring
i++
}else{
print"Error: \"line begin\" must have a restricted translation"
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 2443 "spider.web"

}
}else if($i=="end"){
i++
if($i~/^<.*>$/){
transstring=$i
wherestring="in \"line end\" on line "NR-1
##27:

#line 389 "spider.web"

#line 390 "spider.web"
temp=substr(transstring,2,length(transstring)-2)
trcnt=split(temp,trtok,"-")
outstring=""
for(tridx=1;tridx<=trcnt;tridx++){
alternate=trtok[tridx]
##25:

#line 366 "spider.web"

#line 367 "spider.web"
if(alternate=="space"){
alternate="\" \""
}else if(alternate=="dash"){
alternate="\"-\""
}


##:25

#line 395 "spider.web"

if(alternate~/^[0-9]$/){
print"Digit not allowed in restricted translation",wherestring
exitcode=-1
}else if(alternate~/^[a-zA-Z_]+$/){
print"Key word not allowed in restricted translation",wherestring
exitcode=-1
}else if(alternate~/^\"([^"]*\\\")*[^"]*\"$/){
temp=substr(alternate,2,length(alternate)-2)
outstring=outstring temp
}else if(alternate~/^\*$/){
print"<*> not allowed in restricted translation",wherestring
exitcode=-1
}else{
print"Bogus restricted translation",wherestring
exitcode=-1
}
}
outstring="\""outstring"\""



##:27

#line 2452 "spider.web"

sharp_line_close=outstring
}else{
print"Error: \"line end\" must have a restricted translation"
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 2456 "spider.web"

}
i++
}else{
print"Error: bad line attribute:",$i,"on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 2461 "spider.web"

}
}
##5:

#line 91 "spider.web"

#line 92 "spider.web"
if(i<=NF){
print"Error: leftover fields",$i,"... on line",NR-1
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 94 "spider.web"

}


##:5

#line 2464 "spider.web"

next
}

##:148
##151:

#line 2481 "spider.web"

#line 2482 "spider.web"
/^date /{

mo=month[$3]
day=$4
year=$7
time=$5
##153:

#line 2510 "spider.web"

#line 2511 "spider.web"
hour=substr(time,1,2)
if(hour>=12)
ampm="PM"
else
ampm="AM"

if(hour==0){
hour=12
}else if(hour>12){
hour=hour-12
}
minute=substr(time,4,2)


##:153

#line 2488 "spider.web"

date=sprintf("(generated at %d:%s %s on %s %d, %d)",\
hour,minute,ampm,mo,day,year)
next
}

##:151

#line 60 "spider.web"

##88:

#line 1442 "spider.web"

#line 1443 "spider.web"
/-->/{
##89:

#line 1471 "spider.web"

#line 1472 "spider.web"
lowpos=0;highpos=0;pos=1
prodnum=prodnum+1
inputline[prodnum]=$0
print"Parsing production",prodnum,$0>logfile


##:89

#line 1444 "spider.web"

##90:

#line 1492 "spider.web"

#line 1493 "spider.web"
trans[pos]=""
for(i=1;i<=NF;i++){
if($i~/<.*>/){
##92:

#line 1525 "spider.web"

#line 1526 "spider.web"
transstring=$i
selfstring=""
wherestring=sprintf("in production on line %d",NR-1)
append_keyword="app"
##24:

#line 336 "spider.web"

temp=substr(transstring,2,length(transstring)-2)
trcnt=split(temp,trtok,"-")
outstring=""
for(tridx=1;tridx<=trcnt;tridx++){
alternate=trtok[tridx]
##25:

#line 366 "spider.web"

#line 367 "spider.web"
if(alternate=="space"){
alternate="\" \""
}else if(alternate=="dash"){
alternate="\"-\""
}


##:25

#line 342 "spider.web"

if(alternate~/^[0-9]$/){
temp=sprintf("\tapp_str(\"%s\");\n",alternate)
outstring=outstring temp
}else if(alternate~/^[a-zA-Z_]+$/){
translation_keywords[alternate]=1
temp=sprintf("\t%s(%s);\n",append_keyword,alternate)

outstring=outstring temp
}else if(alternate~/^\"([^"]*\\\")*[^"]*\"$/){
temp=sprintf("\tapp_str(%s);\n",alternate)
outstring=outstring temp
}else if(alternate~/^\*$/){
##26:

#line 377 "spider.web"

#line 378 "spider.web"
if(selfstring==""){
print"Translation \"<*>\" makes no sense",wherestring
exitcode=-1
}

##:26

#line 355 "spider.web"

outstring=outstring selfstring
}else{
print"Bogus translation",wherestring
exitcode=-1
}
}

##:24

#line 1531 "spider.web"

trans[pos]=trans[pos]outstring

##:92

#line 1496 "spider.web"

}else if($i~/^!?[a-zA-Z_]+(\*\*?)?$/){
##93:

#line 1543 "spider.web"

#line 1544 "spider.web"
field[pos]=$i
##96:

#line 1606 "spider.web"

#line 1607 "spider.web"
temp=substr($i,1,1)
if(temp=="!"){
negation=1
$i=substr($i,2)
}else{
negation=0
}

##:96

#line 1545 "spider.web"

##98:

#line 1638 "spider.web"

#line 1639 "spider.web"
if($i~/^([a-zA-Z_]+|\(([a-zA-Z_]+\|)*[a-zA-Z_]+\))\*\*$/){
temp=sprintf("\tmake_underlined(pp+%d);\n",pos-1)
trans[pos]=trans[pos]temp
$i=substr($i,1,length($i)-2)
}else if($i~/^([a-zA-Z_]+|\(([a-zA-Z_]+\|)*[a-zA-Z_]+\))\*$/){
temp=sprintf("\tmake_underlined(pp+%d);\n",pos-1)
trans[pos]=trans[pos]temp
$i=substr($i,1,length($i)-1)
}else if($i~/\*$/){
print"Error: can't remove stars in production on line",NR-1
##91:

#line 1519 "spider.web"

#line 1520 "spider.web"
prodnum--
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 1521 "spider.web"


##:91

#line 1649 "spider.web"

}

##:98

#line 1547 "spider.web"

cat=$i
categories[cat]=1
if(negation==0){
test[pos]=sprintf("(pp+%d)->cat==SP_%s",pos-1,cat)
}else{
test[pos]=sprintf("((pp+%d)->cat!=SP_%s && (pp+%d)->cat != 0)",\
pos-1,cat,pos-1)
}
##95:

#line 1597 "spider.web"

#line 1598 "spider.web"
if(pos>highestpos[cat]){
highestpos[cat]=pos
}

##:95

#line 1556 "spider.web"

##97:

#line 1619 "spider.web"

#line 1620 "spider.web"
pos=pos+1
trans[pos]=""

##:97

#line 1557 "spider.web"


##:93

#line 1498 "spider.web"

}else if($i~/^!?\(([a-zA-Z_]+\|)*[a-zA-Z_]+\)(\*\*?)?$/){
##94:

#line 1567 "spider.web"

#line 1568 "spider.web"
field[pos]=$i
##96:

#line 1606 "spider.web"

#line 1607 "spider.web"
temp=substr($i,1,1)
if(temp=="!"){
negation=1
$i=substr($i,2)
}else{
negation=0
}

##:96

#line 1569 "spider.web"

if(negation==0){
test[pos]="("
}else{
temp=sprintf("(pp+%d)->cat==0",pos-1)
test[pos]="!("temp"||"
}
##98:

#line 1638 "spider.web"

#line 1639 "spider.web"
if($i~/^([a-zA-Z_]+|\(([a-zA-Z_]+\|)*[a-zA-Z_]+\))\*\*$/){
temp=sprintf("\tmake_underlined(pp+%d);\n",pos-1)
trans[pos]=trans[pos]temp
$i=substr($i,1,length($i)-2)
}else if($i~/^([a-zA-Z_]+|\(([a-zA-Z_]+\|)*[a-zA-Z_]+\))\*$/){
temp=sprintf("\tmake_underlined(pp+%d);\n",pos-1)
trans[pos]=trans[pos]temp
$i=substr($i,1,length($i)-1)
}else if($i~/\*$/){
print"Error: can't remove stars in production on line",NR-1
##91:

#line 1519 "spider.web"

#line 1520 "spider.web"
prodnum--
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 1521 "spider.web"


##:91

#line 1649 "spider.web"

}

##:98

#line 1577 "spider.web"

temp=substr($i,2,length($i)-2)
m=split(temp,tok,"|")
for(j=1;j<=m;j++){
cat=tok[j]
categories[cat]=1
##95:

#line 1597 "spider.web"

#line 1598 "spider.web"
if(pos>highestpos[cat]){
highestpos[cat]=pos
}

##:95

#line 1584 "spider.web"

temp=sprintf("(pp+%d)->cat==SP_%s",pos-1,cat)
test[pos]=test[pos]temp
if(j!=m)
test[pos]=test[pos]"||\n"
}
test[pos]=test[pos]")"
##97:

#line 1619 "spider.web"

#line 1620 "spider.web"
pos=pos+1
trans[pos]=""

##:97

#line 1591 "spider.web"



##:94

#line 1500 "spider.web"

}else if($i=="?"){
##99:

#line 1654 "spider.web"

#line 1655 "spider.web"
field[pos]=$i
test[pos]=sprintf("(pp+%d)->cat!=0",pos-1)
highwildcard=pos
##97:

#line 1619 "spider.web"

#line 1620 "spider.web"
pos=pos+1
trans[pos]=""

##:97

#line 1658 "spider.web"




##:99

#line 1502 "spider.web"

}else if($i=="["){
lowpos=pos
}else if($i=="]"){
highpos=pos
}else if($i=="-->"){
break
}else{
print"Error: bad field is",$i,"in production on line",NR-1
##91:

#line 1519 "spider.web"

#line 1520 "spider.web"
prodnum--
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 1521 "spider.web"


##:91

#line 1511 "spider.web"

}
}
i++


##:90

#line 1445 "spider.web"

##100:

#line 1679 "spider.web"

#line 1680 "spider.web"
arrowpos=pos
if(lowpos==0&&highpos==0){
lowpos=1
highpos=arrowpos

}else if(lowpos==0||highpos==0){
print"Error: square brackets don't balance in",\
"production on line",NR-1
##91:

#line 1519 "spider.web"

#line 1520 "spider.web"
prodnum--
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 1521 "spider.web"


##:91

#line 1688 "spider.web"

}

##:100

#line 1446 "spider.web"

##101:

#line 1693 "spider.web"

#line 1694 "spider.web"
if(arrowpos-1>highestposoverall){
highestposoverall=arrowpos-1
}

##:101

#line 1447 "spider.web"

##102:

#line 1708 "spider.web"

#line 1709 "spider.web"
for(hup=arrowpos-1;field[hup]=="?";){
hup--
}
for(;hup>highestunknownpos;hup--){
temp=field[hup]
temp=substr(temp,1,1)
if(temp=="?"||temp=="!"){
highestunknownpos=hup
break
}
}

##:102

#line 1448 "spider.web"

##103:

#line 1722 "spider.web"

#line 1723 "spider.web"
for(pos=1;pos<lowpos;pos++){
##105:

#line 1733 "spider.web"

#line 1734 "spider.web"
if(i>NF||$i!=field[pos]){
print"Error: token mismatch is: found",$i,\
"sought",field[pos],"on line",NR-1
##91:

#line 1519 "spider.web"

#line 1520 "spider.web"
prodnum--
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 1521 "spider.web"


##:91

#line 1737 "spider.web"

}

##:105

#line 1724 "spider.web"

i++
}

##:103

#line 1449 "spider.web"

##106:

#line 1746 "spider.web"

#line 1747 "spider.web"

if(i>NF){
print"Error: no target category in production on line",NR-1
##91:

#line 1519 "spider.web"

#line 1520 "spider.web"
prodnum--
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 1521 "spider.web"


##:91

#line 1750 "spider.web"

}
if($i~/#[0-9]+/){
$i=substr($i,2)
##117:

#line 1867 "spider.web"

#line 1868 "spider.web"
if((0+$i)<1||(0+$i)>=0+arrowpos){
print"Error: can't take token number",$i,"of",arrowpos-1,\
"tokens","in production on line",NR-1
##91:

#line 1519 "spider.web"

#line 1520 "spider.web"
prodnum--
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 1521 "spider.web"


##:91

#line 1871 "spider.web"

}

##:117

#line 1754 "spider.web"

targetcategory[prodnum]="Unnamed category"
temp=sprintf("(pp+%d)->cat",$i-1)
unnamed_cat[prodnum]=temp
}else if($i~/[a-zA-Z][a-zA-Z_]*/){
targetcategory[prodnum]=$i
categories[$i]=1
}else{
print"Error: unrecognizable target token",$i,\
"in production on line",NR-1
##91:

#line 1519 "spider.web"

#line 1520 "spider.web"
prodnum--
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 1521 "spider.web"


##:91

#line 1764 "spider.web"

}
i++

##:106

#line 1450 "spider.web"

##104:

#line 1728 "spider.web"

#line 1729 "spider.web"
for(pos=highpos;pos<arrowpos;pos++){
##105:

#line 1733 "spider.web"

#line 1734 "spider.web"
if(i>NF||$i!=field[pos]){
print"Error: token mismatch is: found",$i,\
"sought",field[pos],"on line",NR-1
##91:

#line 1519 "spider.web"

#line 1520 "spider.web"
prodnum--
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 1521 "spider.web"


##:91

#line 1737 "spider.web"

}

##:105

#line 1730 "spider.web"

i++
}
##:104

#line 1451 "spider.web"

##107:

#line 1769 "spider.web"

#line 1770 "spider.web"
if(i<=NF){
print"Error: used only "i-1" of "NF" tokens",\
"in production on line",NR-1
##91:

#line 1519 "spider.web"

#line 1520 "spider.web"
prodnum--
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 1521 "spider.web"


##:91

#line 1773 "spider.web"

}

##:107

#line 1452 "spider.web"

##108:

#line 1779 "spider.web"

#line 1780 "spider.web"
prodtest[prodnum]=""
for(pos=1;pos<arrowpos;pos++){
if(pos>1){
prodtest[prodnum]=prodtest[prodnum]" &&\n\t\t"
}
prodtest[prodnum]=prodtest[prodnum]test[pos]
}

##:108

#line 1454 "spider.web"

##109:

#line 1789 "spider.web"

#line 1790 "spider.web"
prodtrans[prodnum]=""
for(pos=lowpos;pos<highpos;pos++){
prodtrans[prodnum]=prodtrans[prodnum]trans[pos]

temp=sprintf("\tapp1(pp+%d);\n",pos-1)
prodtrans[prodnum]=prodtrans[prodnum]temp
##114:

#line 1830 "spider.web"

#line 1831 "spider.web"
temp=field[pos]
tempa=substr(temp,1,1)
if(tempa!="!"){
if(temp~/^\(([a-zA-Z_]+\|)*[a-zA-Z_]+\)(\*\*?)?$/){

##115:

#line 1853 "spider.web"

#line 1854 "spider.web"
while(temp~/\*$/){
temp=substr(temp,1,length(temp)-1)
}

##:115

#line 1836 "spider.web"

temp=substr(temp,2,length(temp)-2)
m=split(temp,tok,"|")
for(j=1;j<=m;j++){
alternate=tok[j]
reduced[alternate]=1
}
}else if(temp~/^[a-zA-Z_]+(\*\*?)?$/){
##115:

#line 1853 "spider.web"

#line 1854 "spider.web"
while(temp~/\*$/){
temp=substr(temp,1,length(temp)-1)
}

##:115

#line 1844 "spider.web"

reduced[temp]=1
}else if(temp!="?"){
print"Confusion: unintelligible field[pos]:",temp,\
"in production on line",NR-1
##91:

#line 1519 "spider.web"

#line 1520 "spider.web"
prodnum--
##4:

#line 79 "spider.web"

#line 80 "spider.web"
exitcode=-1
next


##:4

#line 1521 "spider.web"


##:91

#line 1849 "spider.web"

}
}

##:114

#line 1798 "spider.web"

}
prodtrans[prodnum]=prodtrans[prodnum]trans[highpos]

##:109

#line 1456 "spider.web"

##110:

#line 1803 "spider.web"

#line 1804 "spider.web"
ppstart[prodnum]=lowpos-1
tokensreduced[prodnum]=highpos-lowpos

##:110

#line 1458 "spider.web"

##111:

#line 1808 "spider.web"

#line 1809 "spider.web"
if(highpos-lowpos==1){
printf"%d: %s --> %s\n",prodnum,field[lowpos],\
targetcategory[prodnum]>cycles
wrotecycles=1
}

##:111

#line 1460 "spider.web"

next
}

##:88

#line 61 "spider.web"

##7:

#line 108 "spider.web"

#line 109 "spider.web"
{
print"Warning: I don't know what to do with this line:"
print"        ",$0
print"Warning: I don't know what to do with this line:">logfile
print"        ",$0>logfile
}


##:7

#line 62 "spider.web"


END{
##54:

#line 847 "spider.web"

#line 848 "spider.web"
tempfile=scrapfile
##55:

#line 854 "spider.web"

#line 855 "spider.web"
print"@ Here we input tokens of more than one character">tempfile
print"@<Compress two-symbol operator@>=">tempfile
##56:

#line 863 "spider.web"

#line 864 "spider.web"
for(len=maxtokenlength;len>=2;len--){
printf"if (loc+%d<=limit) {\n",len-1>tempfile
##57:

#line 871 "spider.web"

#line 872 "spider.web"
notfirst=0
for(t in tokentest){
if(tokenlength[t]==len){
printf"\t">tempfile
if(notfirst==1){
printf"else ">tempfile
}
notfirst=1
printf"if (%s) {\n",tokentest[t]>tempfile
printf"\t\tloc += %d;\n",len-1>tempfile
printf"\t\treturn %s;\n\t\t}\n",tokenname[t]>tempfile
}
}


##:57

#line 866 "spider.web"

printf"\t}\n">tempfile
}
##58:

#line 887 "spider.web"

#line 888 "spider.web"
for(t in tokentest){
if(tokenlength[t]==1){
print"This can't happen: token",t,"is of length 1 but",\
"it has a test"
exitcode=-1
}
}



##:58

#line 869 "spider.web"


##:56

#line 858 "spider.web"


##:55

#line 849 "spider.web"

tempfile=ttokfile
##55:

#line 854 "spider.web"

#line 855 "spider.web"
print"@ Here we input tokens of more than one character">tempfile
print"@<Compress two-symbol operator@>=">tempfile
##56:

#line 863 "spider.web"

#line 864 "spider.web"
for(len=maxtokenlength;len>=2;len--){
printf"if (loc+%d<=limit) {\n",len-1>tempfile
##57:

#line 871 "spider.web"

#line 872 "spider.web"
notfirst=0
for(t in tokentest){
if(tokenlength[t]==len){
printf"\t">tempfile
if(notfirst==1){
printf"else ">tempfile
}
notfirst=1
printf"if (%s) {\n",tokentest[t]>tempfile
printf"\t\tloc += %d;\n",len-1>tempfile
printf"\t\treturn %s;\n\t\t}\n",tokenname[t]>tempfile
}
}


##:57

#line 866 "spider.web"

printf"\t}\n">tempfile
}
##58:

#line 887 "spider.web"

#line 888 "spider.web"
for(t in tokentest){
if(tokenlength[t]==1){
print"This can't happen: token",t,"is of length 1 but",\
"it has a test"
exitcode=-1
}
}



##:58

#line 869 "spider.web"


##:56

#line 858 "spider.web"


##:55

#line 851 "spider.web"


##:54
##59:

#line 904 "spider.web"

#line 905 "spider.web"
print"Writing out predefined scraps">logfile
##60:

#line 917 "spider.web"

#line 918 "spider.web"
if(id_category!=""){
print"@ @<Append an identifier scrap@>=">scrapfile
print"p=id_lookup(id_first, id_loc,normal);">scrapfile
print"if (p->ilk==normal) {">scrapfile
print"  small_app(id_flag+p-name_dir);">scrapfile
printf"  app_scrap(SP_%s,%s_math);",\
id_category,id_mathness>scrapfile
appended[id_category]=1
print" /* not a reserved word */">scrapfile
print"}">scrapfile
print"else if reserved(p) {">scrapfile
print"@<Decide on reserved word scraps@>;">scrapfile
print"}">scrapfile
print"else {">scrapfile
print" err_print(\"! Identifier with unmentioned ilk\");">scrapfile
print"@.Identifier with unmentioned ilk@>">scrapfile
print"}">scrapfile
}else{
print"Error: I don't know what to do with an identifier"
print"       Please give me a \"token identifier ...\""
exitcode=-1
}

##:60

#line 906 "spider.web"

##62:

#line 948 "spider.web"

#line 949 "spider.web"
print"Warning: TeX strings have the same category as ",\
"numeric constants in this WEAVE."
print"Warning: TeX strings have the same category as ",\
"numeric constants in this WEAVE.">logfile
if(number_category!=""){
print"@ For some reason strings, constants,",\
" and \TeX\ strings are identified.">scrapfile
print"That has to be fixed.">scrapfile
print"@<Do the |app_scrap| for a string or constant@>=">scrapfile
printf"app_scrap(SP_%s,%s_math);\n",number_category,\
number_mathness>scrapfile
appended[number_category]=1
}else{
print"Error: I don't know what to do with a numeric constant"
print"       Please give me a \"token number ...\""
exitcode=-1
}


##:62

#line 907 "spider.web"

##64:

#line 977 "spider.web"

#line 978 "spider.web"
if(newline_category!=""){
print"@ @<Append a newline scrap@>=">scrapfile
transstring=newline_translation
selfstring="small_app(next_control);"
wherestring="in translation of token newline"
append_keyword="small_app"
##24:

#line 336 "spider.web"

temp=substr(transstring,2,length(transstring)-2)
trcnt=split(temp,trtok,"-")
outstring=""
for(tridx=1;tridx<=trcnt;tridx++){
alternate=trtok[tridx]
##25:

#line 366 "spider.web"

#line 367 "spider.web"
if(alternate=="space"){
alternate="\" \""
}else if(alternate=="dash"){
alternate="\"-\""
}


##:25

#line 342 "spider.web"

if(alternate~/^[0-9]$/){
temp=sprintf("\tapp_str(\"%s\");\n",alternate)
outstring=outstring temp
}else if(alternate~/^[a-zA-Z_]+$/){
translation_keywords[alternate]=1
temp=sprintf("\t%s(%s);\n",append_keyword,alternate)

outstring=outstring temp
}else if(alternate~/^\"([^"]*\\\")*[^"]*\"$/){
temp=sprintf("\tapp_str(%s);\n",alternate)
outstring=outstring temp
}else if(alternate~/^\*$/){
##26:

#line 377 "spider.web"

#line 378 "spider.web"
if(selfstring==""){
print"Translation \"<*>\" makes no sense",wherestring
exitcode=-1
}

##:26

#line 355 "spider.web"

outstring=outstring selfstring
}else{
print"Bogus translation",wherestring
exitcode=-1
}
}

##:24

#line 985 "spider.web"

print outstring>scrapfile
printf"  app_scrap(SP_%s,%s_math);\n",newline_category,\
newline_mathness>scrapfile
appended[newline_category]=1
}else{
print"Error: I don't know what to do with a newline"
print"       Please give me a \"token newline ...\""
exitcode=-1
}

##:64

#line 908 "spider.web"

##65:

#line 997 "spider.web"

#line 998 "spider.web"
if(pseudo_semi_category!=""){
print"@ @<Append a |pseudo_semi| scrap@>=">scrapfile
transstring=pseudo_semi_translation
selfstring="small_app(next_control);"
wherestring="in translation of token pseudo_semi"
append_keyword="small_app"
##24:

#line 336 "spider.web"

temp=substr(transstring,2,length(transstring)-2)
trcnt=split(temp,trtok,"-")
outstring=""
for(tridx=1;tridx<=trcnt;tridx++){
alternate=trtok[tridx]
##25:

#line 366 "spider.web"

#line 367 "spider.web"
if(alternate=="space"){
alternate="\" \""
}else if(alternate=="dash"){
alternate="\"-\""
}


##:25

#line 342 "spider.web"

if(alternate~/^[0-9]$/){
temp=sprintf("\tapp_str(\"%s\");\n",alternate)
outstring=outstring temp
}else if(alternate~/^[a-zA-Z_]+$/){
translation_keywords[alternate]=1
temp=sprintf("\t%s(%s);\n",append_keyword,alternate)

outstring=outstring temp
}else if(alternate~/^\"([^"]*\\\")*[^"]*\"$/){
temp=sprintf("\tapp_str(%s);\n",alternate)
outstring=outstring temp
}else if(alternate~/^\*$/){
##26:

#line 377 "spider.web"

#line 378 "spider.web"
if(selfstring==""){
print"Translation \"<*>\" makes no sense",wherestring
exitcode=-1
}

##:26

#line 355 "spider.web"

outstring=outstring selfstring
}else{
print"Bogus translation",wherestring
exitcode=-1
}
}

##:24

#line 1005 "spider.web"

print outstring>scrapfile
printf"  app_scrap(SP_%s,%s_math);\n",pseudo_semi_category,\
pseudo_semi_mathness>scrapfile
appended[pseudo_semi_category]=1
}else{
printf"Error: I don't know what to do with a pseudo_semi (%s;)",\
substr(at_sign,1,1)
print"       Please give me a \"token pseudo_semi ...\""
exitcode=-1
}

##:65

#line 909 "spider.web"

print"Writing out token scraps">logfile
##66:

#line 1018 "spider.web"

#line 1019 "spider.web"
print"@ @<Cases for ordinary tokens@>=">scrapfile
for(t in tokens){
temp=tokenname[t]
printf"case %s:\n",temp>scrapfile
transstring=tokentranslation[t]
selfstring="small_app(next_control);"
wherestring=sprintf("in translation of token %s",t)
append_keyword="small_app"
##24:

#line 336 "spider.web"

temp=substr(transstring,2,length(transstring)-2)
trcnt=split(temp,trtok,"-")
outstring=""
for(tridx=1;tridx<=trcnt;tridx++){
alternate=trtok[tridx]
##25:

#line 366 "spider.web"

#line 367 "spider.web"
if(alternate=="space"){
alternate="\" \""
}else if(alternate=="dash"){
alternate="\"-\""
}


##:25

#line 342 "spider.web"

if(alternate~/^[0-9]$/){
temp=sprintf("\tapp_str(\"%s\");\n",alternate)
outstring=outstring temp
}else if(alternate~/^[a-zA-Z_]+$/){
translation_keywords[alternate]=1
temp=sprintf("\t%s(%s);\n",append_keyword,alternate)

outstring=outstring temp
}else if(alternate~/^\"([^"]*\\\")*[^"]*\"$/){
temp=sprintf("\tapp_str(%s);\n",alternate)
outstring=outstring temp
}else if(alternate~/^\*$/){
##26:

#line 377 "spider.web"

#line 378 "spider.web"
if(selfstring==""){
print"Translation \"<*>\" makes no sense",wherestring
exitcode=-1
}

##:26

#line 355 "spider.web"

outstring=outstring selfstring
}else{
print"Bogus translation",wherestring
exitcode=-1
}
}

##:24

#line 1028 "spider.web"

print outstring>scrapfile
printf"\tapp_scrap(SP_%s,%s_math);\n",tokencategory[t],\
tokenmathness[t]>scrapfile
temp=tokencategory[t]
appended[temp]=1

print"\tbreak;">scrapfile
}

##:66

#line 911 "spider.web"





##:59
##67:

#line 1047 "spider.web"

#line 1048 "spider.web"
print"@ @<Cases for tokens to be output@>=">ttokfile
for(t in tokennumbers){
##69:

#line 1099 "spider.web"

#line 1100 "spider.web"
if(t=="string"||t=="constant"||t=="identifier")
continue



##:69

#line 1050 "spider.web"

printf"case %s:\n",tokenname[t]>ttokfile
this_tangleto=tokentangleto[t]
if(this_tangleto==""){
printf"\tC_printf(\"%%s\",\"%s\");\n",t>ttokfile
}else{
printf"\tif (out_state==verbatim) {\n">ttokfile
printf"\t\tC_printf(\"%%s\",\"%s\");\n",t>ttokfile
printf"\t} else {\n">ttokfile
##70:

#line 1106 "spider.web"

#line 1107 "spider.web"
oldwherestring=wherestring
wherestring="for tangleto "wherestring

transstring=this_tangleto
##27:

#line 389 "spider.web"

#line 390 "spider.web"
temp=substr(transstring,2,length(transstring)-2)
trcnt=split(temp,trtok,"-")
outstring=""
for(tridx=1;tridx<=trcnt;tridx++){
alternate=trtok[tridx]
##25:

#line 366 "spider.web"

#line 367 "spider.web"
if(alternate=="space"){
alternate="\" \""
}else if(alternate=="dash"){
alternate="\"-\""
}


##:25

#line 395 "spider.web"

if(alternate~/^[0-9]$/){
print"Digit not allowed in restricted translation",wherestring
exitcode=-1
}else if(alternate~/^[a-zA-Z_]+$/){
print"Key word not allowed in restricted translation",wherestring
exitcode=-1
}else if(alternate~/^\"([^"]*\\\")*[^"]*\"$/){
temp=substr(alternate,2,length(alternate)-2)
outstring=outstring temp
}else if(alternate~/^\*$/){
print"<*> not allowed in restricted translation",wherestring
exitcode=-1
}else{
print"Bogus restricted translation",wherestring
exitcode=-1
}
}
outstring="\""outstring"\""



##:27

#line 1112 "spider.web"

printf"\tC_printf(\"%%s\",%s);\n",outstring>ttokfile

wherestring=oldwherestring



##:70

#line 1059 "spider.web"

printf"\t}\n">ttokfile
}
print"\tif (out_state!=verbatim) out_state=misc;">ttokfile
print"break;">ttokfile
}

##:67
##68:

#line 1068 "spider.web"

#line 1069 "spider.web"
print"@ @<Cases for tokens to be output@>=">ttokfile
for(t in tokentangleto){
##69:

#line 1099 "spider.web"

#line 1100 "spider.web"
if(t=="string"||t=="constant"||t=="identifier")
continue



##:69

#line 1071 "spider.web"

if(tokennumbers[t]!=""||tokentangleto[t]=="")
continue
if(t=="@"){
thistangletokname="@@"
}else if(t=="\\"||t=="'"){
thistangletokname="\\"t
}else{
thistangletokname=t
}
printf"case '%s':\n",thistangletokname>ttokfile
this_tangleto=tokentangleto[t]
if(this_tangleto==""){
print"This can't happen -- null tangleto for",t,wherestring
exitcode=-1
}else{
printf"\tif (out_state==verbatim) {\n">ttokfile
printf"\t\tC_printf(\"%%s\",\"%s\");\n",t>ttokfile
printf"\t} else {\n">ttokfile
##70:

#line 1106 "spider.web"

#line 1107 "spider.web"
oldwherestring=wherestring
wherestring="for tangleto "wherestring

transstring=this_tangleto
##27:

#line 389 "spider.web"

#line 390 "spider.web"
temp=substr(transstring,2,length(transstring)-2)
trcnt=split(temp,trtok,"-")
outstring=""
for(tridx=1;tridx<=trcnt;tridx++){
alternate=trtok[tridx]
##25:

#line 366 "spider.web"

#line 367 "spider.web"
if(alternate=="space"){
alternate="\" \""
}else if(alternate=="dash"){
alternate="\"-\""
}


##:25

#line 395 "spider.web"

if(alternate~/^[0-9]$/){
print"Digit not allowed in restricted translation",wherestring
exitcode=-1
}else if(alternate~/^[a-zA-Z_]+$/){
print"Key word not allowed in restricted translation",wherestring
exitcode=-1
}else if(alternate~/^\"([^"]*\\\")*[^"]*\"$/){
temp=substr(alternate,2,length(alternate)-2)
outstring=outstring temp
}else if(alternate~/^\*$/){
print"<*> not allowed in restricted translation",wherestring
exitcode=-1
}else{
print"Bogus restricted translation",wherestring
exitcode=-1
}
}
outstring="\""outstring"\""



##:27

#line 1112 "spider.web"

printf"\tC_printf(\"%%s\",%s);\n",outstring>ttokfile

wherestring=oldwherestring



##:70

#line 1090 "spider.web"

printf"\t}\n">ttokfile
}
print"\tif (out_state!=verbatim) out_state=misc;">ttokfile
print"break;">ttokfile
}
##:68
##71:

#line 1123 "spider.web"

#line 1124 "spider.web"
tempfile=scrapfile
##72:

#line 1131 "spider.web"

#line 1132 "spider.web"
print"@ Here are the definitions of the token names">tempfile
for(t in tokennumbers){
temp=tokennumbers[t]
if(temp==0)
continue
if(tempfile==ttokfile){
##69:

#line 1099 "spider.web"

#line 1100 "spider.web"
if(t=="string"||t=="constant"||t=="identifier")
continue



##:69

#line 1139 "spider.web"

temp=temp+31+3-highesttoken

}
printf"@d %s = %s\n",tokenname[t],temp>tempfile
}


##:72

#line 1125 "spider.web"

tempfile=ttokfile
##72:

#line 1131 "spider.web"

#line 1132 "spider.web"
print"@ Here are the definitions of the token names">tempfile
for(t in tokennumbers){
temp=tokennumbers[t]
if(temp==0)
continue
if(tempfile==ttokfile){
##69:

#line 1099 "spider.web"

#line 1100 "spider.web"
if(t=="string"||t=="constant"||t=="identifier")
continue



##:69

#line 1139 "spider.web"

temp=temp+31+3-highesttoken

}
printf"@d %s = %s\n",tokenname[t],temp>tempfile
}


##:72

#line 1127 "spider.web"


##:71
##79:

#line 1268 "spider.web"

#line 1269 "spider.web"
print"Writing out reserved words and ilks">logfile
ilkno=64
print"@ Here is a list of all the ilks">reserved
for(i in ilk_translation){
printf"@d SP_%s = %d\n",i,ilkno>reserved
ilkno++
}

##:79
##80:

#line 1279 "spider.web"

#line 1280 "spider.web"
print" ">reserved
print"@ Here are the scraps we get from the reserved words">reserved
print"@d the_word = res_flag+p-name_dir">reserved
print"@<Decide on reserved word scraps@>=">reserved
print"switch (p->ilk) {">reserved
for(t in ilk_translation){
printf"\tcase SP_%s: \n\t\t",t>reserved
transstring=ilk_translation[t]
selfstring="small_app(the_word);"
wherestring=sprintf("in translation of ilk %s",t)
append_keyword="small_app"
##24:

#line 336 "spider.web"

temp=substr(transstring,2,length(transstring)-2)
trcnt=split(temp,trtok,"-")
outstring=""
for(tridx=1;tridx<=trcnt;tridx++){
alternate=trtok[tridx]
##25:

#line 366 "spider.web"

#line 367 "spider.web"
if(alternate=="space"){
alternate="\" \""
}else if(alternate=="dash"){
alternate="\"-\""
}


##:25

#line 342 "spider.web"

if(alternate~/^[0-9]$/){
temp=sprintf("\tapp_str(\"%s\");\n",alternate)
outstring=outstring temp
}else if(alternate~/^[a-zA-Z_]+$/){
translation_keywords[alternate]=1
temp=sprintf("\t%s(%s);\n",append_keyword,alternate)

outstring=outstring temp
}else if(alternate~/^\"([^"]*\\\")*[^"]*\"$/){
temp=sprintf("\tapp_str(%s);\n",alternate)
outstring=outstring temp
}else if(alternate~/^\*$/){
##26:

#line 377 "spider.web"

#line 378 "spider.web"
if(selfstring==""){
print"Translation \"<*>\" makes no sense",wherestring
exitcode=-1
}

##:26

#line 355 "spider.web"

outstring=outstring selfstring
}else{
print"Bogus translation",wherestring
exitcode=-1
}
}

##:24

#line 1293 "spider.web"

if(trcnt>0)
has_translation[t]=1
print outstring>reserved
printf"\tapp_scrap(SP_%s,%s_math);\n",ilk_category[t],\
ilk_mathness[t]>reserved
temp=ilk_category[t]
appended[temp]=1

printf"\t\tbreak;\n">reserved
}
print"}">reserved


##:80
##81:

#line 1309 "spider.web"

#line 1310 "spider.web"
print"@ @<Store all the reserved words@>=">reserved
for(i in reservedilk){
printf"id_lookup(\"%s\",NULL,SP_%s);\n",i,reservedilk[i]>reserved
}

##:81
##118:

#line 1876 "spider.web"

#line 1877 "spider.web"
print"Writing out category codes">logfile
print"@ Here is a list of category codes scraps can have">grammarfile
i=1
for(t in categories){
printf"@d SP_%s = %d\n",t,i>grammarfile
i++
}
print"@c">grammarfile
##:118
##119:

#line 1887 "spider.web"

#line 1888 "spider.web"
print"#ifdef DEBUG">grammarfile
print"#define PRINT_CAT(A,B) case A: printf(B); break">grammarfile
print"print_cat(c) /* symbolic printout of a category */">grammarfile
print"eight_bits c;">grammarfile
print"{">grammarfile
print"  switch(c) {">grammarfile
for(t in categories){
printf"PRINT_CAT(SP_%s,\"%s\");\n",t,t>grammarfile
}
print"    case 0: printf(\"zero\"); break;">grammarfile
print"    default: printf(\"UNKNOWN\"); break;">grammarfile
print"  }">grammarfile
print"}">grammarfile
print"#endif DEBUG">grammarfile
print" ">grammarfile

##:119
##123:

#line 1947 "spider.web"

#line 1948 "spider.web"
print"Writing out grammar">logfile
print"@ Here is where we define |highestposoverall| and where we">grammarfile
print"check the productions.">grammarfile
print"@d highestposoverall =",highestposoverall>grammarfile
print"@<Test for all of the productions@>=">grammarfile
for(n=1;n<=prodnum;n++){
if(n%5==0)
print"@ @<Test for all of the productions@>="\
>grammarfile
##126:

#line 2011 "spider.web"

#line 2012 "spider.web"
this_string=inputline[n]
tempi=index(this_string,"|")
while(tempi!=0){
tempa=substr(this_string,1,tempi-1)
tempb=substr(this_string,tempi+1)
this_string=tempa"\\vert "tempb
tempi=index(this_string,"|")
}
templ="";tempr=this_string
tempi=index(tempr,"_")
while(tempi!=0){
tempa=substr(tempr,1,tempi-1)
tempr=substr(tempr,tempi+1)
templ=templ tempa"\\_"
tempi=index(tempr,"_")
}
this_string=templ tempr
templ="";tempr=this_string
tempi=index(tempr,"#")
while(tempi!=0){
tempa=substr(tempr,1,tempi-1)
tempr=substr(tempr,tempi+1)
templ=templ tempa"\\#"
tempi=index(tempr,"#")
}
this_string=templ tempr


##:126

#line 1957 "spider.web"

##127:

#line 2041 "spider.web"

#line 2042 "spider.web"
toolong=this_string;this_string=""
while(length(toolong)>60){
idx=59
idchar=substr(toolong,idx,1)
while(idx>1&&idchar!=" "){
idx--
idchar=substr(toolong,idx,1)
}
if(idx==1)
idx=59
temp=substr(toolong,1,idx-1)
toolong=substr(toolong,idx+1)
this_string=this_string temp"\n"
}
this_string=this_string toolong



##:127

#line 1958 "spider.web"

printf"if (%s) {\n\t/* %d: {\\tt %s} */\n%s",\
prodtest[n],n,this_string,prodtrans[n]>grammarfile
##124:

#line 1970 "spider.web"

#line 1971 "spider.web"
ttk=targetcategory[n]
if(ttk=="Unnamed category"){

printf"\treduce(pp+%d,%d,%s,%d,%d);\n",ppstart[n],\
tokensreduced[n],unnamed_cat[n],\
1-highestposoverall,n>grammarfile
}else{
appended[ttk]=1

reduction=highestpos[ttk]
if(reduction<highestunknownpos){
reduction=highestunknownpos
}
printf"\treduce(pp+%d,%d,SP_%s,%d,%d);\n",ppstart[n],\
tokensreduced[n],targetcategory[n],\
1-reduction,n>grammarfile
}

##:124

#line 1962 "spider.web"

print"\tgoto end_prods;">grammarfile
printf"} ">grammarfile
}
printf"\n">grammarfile
print"end_prods:">grammarfile

##:123
##130:

#line 2095 "spider.web"

#line 2096 "spider.web"
if(language!=""){
print"@ Here is the language-dependent stuff">tlang
if(version!="")
version=", Version "version
printf"@d banner = \"This is %s TANGLE%s %s\\n\"\n",language,\
version,date>tlang
printf"@<Global...@>=char C_file_extension[]=\"%s\";\n",extension \
>tlang

print"@ Here is the language-dependent stuff">wlang
if(version!="")
version=", Version "version
printf"@d banner = \"This is %s WEAVE%s %s\\n\"\n",language,\
version,date>wlang
print"@<Set |out_ptr| and do a |tex_printf| to read the macros@>="\
>wlang
printf"*out_ptr='x'; tex_printf(\"\\\\input %sweb.te\");\n",\
extension>wlang
printf"@ @<Global...@>=char C_file_extension[]=\"%s\";\n",extension \
>wlang
}else{
print"Error: you haven't given me any \"language\" information"
exitcode=-1
}

##:130
##134:

#line 2189 "spider.web"

#line 2190 "spider.web"
if(mod_def_cat!=""){
print"@ @<Call |app_scrap| for a module definition@>=">scrapfile
printf"app_scrap(SP_%s,no_math);\n",mod_def_cat>scrapfile
appended[mod_def_cat]=1
}else{
print"Error: I don't know what to do with a module definition"
print"       Give me a \"module definition ...\""
exitcode=-1
}
if(mod_use_cat!=""){
print"@ @<Call |app_scrap| for a module use@>=">scrapfile
printf"app_scrap(SP_%s,maybe_math);\n",mod_use_cat>scrapfile
appended[mod_use_cat]=1
}else{
print"Error: I don't know what to do with a module use"
print"       Give me a \"module use ...\""
exitcode=-1
}


##:134
##136:

#line 2230 "spider.web"

#line 2231 "spider.web"
tempfile=grammarfile
##137:

#line 2237 "spider.web"

#line 2238 "spider.web"
print"@ Here is the |at_sign| for the new web">tempfile
printf"@d at_sign = @`%s'\n",at_sign>tempfile
print" ">tempfile
print"@ Here is |the_at_sign| left for common">tempfile
print"@<Global...@>=char the_at_sign = at_sign;">tempfile
print" ">tempfile

##:137

#line 2232 "spider.web"

tempfile=ttokfile
##137:

#line 2237 "spider.web"

#line 2238 "spider.web"
print"@ Here is the |at_sign| for the new web">tempfile
printf"@d at_sign = @`%s'\n",at_sign>tempfile
print" ">tempfile
print"@ Here is |the_at_sign| left for common">tempfile
print"@<Global...@>=char the_at_sign = at_sign;">tempfile
print" ">tempfile

##:137

#line 2234 "spider.web"


##:136
##140:

#line 2304 "spider.web"

#line 2305 "spider.web"
print"@ Here we recognize the comment start seqence">ttokfile
print"@<See a comment starting at |loc| and skip it@>=">ttokfile
printf"{int len; len=strlen(%s);\n",begin_comment_string>ttokfile
printf"if (loc+len<=limit && !strncmp(loc,%s,len)) {\n",\
begin_comment_string>ttokfile
print"\tloc += len; /* a new thing */">ttokfile
print"\tskip_comment(); /* scan to end of comment or newline */">ttokfile
print"\tif (comment_continues || comments_end_with_newline)">ttokfile
print"\t\treturn('\\n');">ttokfile
print"\telse continue;\n}\n}">ttokfile


##:140
##141:

#line 2318 "spider.web"

#line 2319 "spider.web"
print"@ @<See a comment starting at |loc-1| and return |begin_comment|@>="\
>scrapfile
printf"{int len; len=strlen(%s);\n",begin_comment_string>scrapfile
printf"if (loc+len-1<=limit && !strncmp(loc-1,%s,len)) {\n",\
begin_comment_string>scrapfile
print"\tloc += len-1;">scrapfile
print"\t return (begin_comment); /* scan to end of comment or newline */">scrapfile
print"}\n}">scrapfile




##:141
##142:

#line 2332 "spider.web"

#line 2333 "spider.web"
print"@ Here we deal with recognizing the end of comments">ttokfile
printf"@d comments_end_with_newline = %d\n",comments_end_with_newline>ttokfile
print"@<Recognize comment end starting at |loc-1|@>=">ttokfile
if(comments_end_with_newline!=1){
printf"{int len; len=strlen(%s);\n",end_comment_string>ttokfile
printf"if (loc+len-1<=limit && !strncmp(loc-1,%s,len)) {\n",\
end_comment_string>ttokfile
print"loc += len-1; return(comment_continues=0); }}">ttokfile
}else{
print"/* This code will never be executed */ ">ttokfile
}

##:142
##143:

#line 2348 "spider.web"

#line 2349 "spider.web"
printf"@ Here we recognize end of comments">scrapfile
printf"@d comments_end_with_newline = %d\n",comments_end_with_newline>scrapfile
print"@<Check for end of comment@>=">scrapfile
printf"{int len; len=strlen(%s);\n",end_comment_string>scrapfile
printf"if (loc+len-1<=limit && !strncmp(loc-1,%s,len)) {\n",\
end_comment_string>scrapfile
print" loc++; if(bal==1) {if (phase==2) app_tok('}'); return(0);}">scrapfile
print"  else {">scrapfile
print"    err_print(\"! Braces don't balance in comment\");">scrapfile
print"@.Braces don't balance in comment@>">scrapfile
print"    @<Clear |bal| and |return|@>;">scrapfile
print"  }">scrapfile
print"}">scrapfile
print"}">scrapfile


##:143
##144:

#line 2367 "spider.web"

#line 2368 "spider.web"
print"@ Important tokens:">ttokfile
printf"@d begin_comment_string = %s\n",begin_comment_string>ttokfile
printf"@d end_comment_string = %s\n",end_comment_string>ttokfile

##:144
##149:

#line 2469 "spider.web"

#line 2470 "spider.web"
print"@ Important tokens:">ttokfile
printf"@d sharp_line_open = %s\n",sharp_line_open>ttokfile
printf"@d sharp_line_close = %s\n",sharp_line_close>ttokfile

##:149

#line 65 "spider.web"

print"Writing out lists">logfile
##21:

#line 304 "spider.web"

#line 305 "spider.web"
for(t in translation_keywords){
print t>translationfile
}

##:21
##73:

#line 1149 "spider.web"

#line 1150 "spider.web"
for(t in tokenname){
temp=tokenname[t]
if(substr(temp,1,1)!="'"){
##74:

#line 1158 "spider.web"

#line 1159 "spider.web"
tempa=substr(temp,1,3)
if(tempa=="SP_"){
temp=substr(temp,4)
}


##:74

#line 1153 "spider.web"

print temp>tokennamefile
}
}

##:73
##83:

#line 1330 "spider.web"

#line 1331 "spider.web"
for(i in ilk_translation){
print i>ilkfile
}

##:83
##113:

#line 1817 "spider.web"

#line 1818 "spider.web"
if(wrotecycles==0){
print"0: dummy --> nodummy">cycles
}

##:113
##120:

#line 1905 "spider.web"

#line 1906 "spider.web"
for(c in categories){
print c>categoryfile
}

##:120
##122:

#line 1929 "spider.web"

#line 1930 "spider.web"
for(n=1;n<=prodnum;n++){
printf"%2d: %s\n",n,inputline[n]>productions
}

##:122

#line 67 "spider.web"

##22:

#line 309 "spider.web"

#line 310 "spider.web"
for(t in translation_keywords){
num_of_translation_keywords++
}
printf"You used %d translation keywords.\n",\
num_of_translation_keywords>logfile
printf"You used %d translation keywords.\n",num_of_translation_keywords

##:22
##84:

#line 1335 "spider.web"

#line 1336 "spider.web"
for(i in ilk_translation)number_of_ilks++
for(i in reservedilk)number_of_reserved_words++
printf"You defined %d reserved words of %d ilks.\n",\
number_of_reserved_words,number_of_ilks
printf"You defined %d reserved words of %d ilks.\n",\
number_of_reserved_words,number_of_ilks>logfile

##:84
##121:

#line 1910 "spider.web"

#line 1911 "spider.web"
for(c in categories){
number_of_categories++
}
printf"You used %d different categories in %d productions.\n",\
number_of_categories,prodnum
printf"You used %d different categories in %d productions.\n",\
number_of_categories,prodnum>logfile
printf"The biggest production had %d scraps on its left-hand side.\n",\
highestposoverall
printf"The biggest production had %d scraps on its left-hand side.\n",\
highestposoverall>logfile


##:121

#line 68 "spider.web"

##47:

#line 734 "spider.web"

#line 735 "spider.web"
if(tokennumber<127){
print"Error: too many token names for WEAVE --- over by",\
127-tokennumber
exitcode=-1
}
##:47
##48:

#line 743 "spider.web"

#line 744 "spider.web"
if(highesttoken-tokennumber>31-(11-1)+3){\

print"Error: too many token names for TANGLE --- over by",\
highesttoken-tokennumber-(31-(11-1)+3)
exitcode=-1
}



##:48
##82:

#line 1318 "spider.web"

#line 1319 "spider.web"
for(i in ilk_translation){
if(has_reserved[i]!=1){
print"Error: there is no reserved word of ilk",i
exitcode=-1
}
if(has_translation[i]!=1){
print"Error: ilk",i,"has no translation"
exitcode=-1
}
}

##:82
##116:

#line 1858 "spider.web"

#line 1859 "spider.web"
for(c in categories){
if(reduced[c]!=1){
print"Warning: category",c,"never reduced"
}
}


##:116
##125:

#line 1992 "spider.web"

#line 1993 "spider.web"
for(c in categories){
if(appended[c]!=1){
if(c=="ignore_scrap"){
print"Warning: category",c,"never appended"
}else{
print"Error: category",c,"never appended"
exitcode=-1
}
}
}



##:125

#line 69 "spider.web"

if(exitcode!=0){
exit exitcode
}
}

##:3

